server:
  port: 7003
eureka:
  instance:
    hostname: eureka03.com
  client:
    service-url:
      defaultZone: http://eureka01.com/eureka,http://eureka02.com/eureka
    register-with-eureka: false
    fetch-registry: false